name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mqtt-client-Android

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./mqtt-client-Android
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./mqtt-client-Android
      run: ./gradlew build
    - name: Ls
      working-directory: ./mqtt-client-Android
      run: ls app/build/outputs/apk/debug/
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ./mqtt-client-Android/app/build/outputs/apk/debug/app-debug.apk

