name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Echo
      run: pwd
    - name: Grant execute permission for gradlew
      run: chmod +x ./mqtt-client-Android/gradlew
    - name: Build with Gradle
      run: ./mqtt-client-Android/gradlew build
    - name: Ls
      run: ls ./mqtt-client-Android
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/mqtt-client-Android/app/build/outputs/apk/debug/app-debug.apk

