name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: gradlew build
    - name: Ls
      run: ls app
    - name: upload result
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

